### PR TITLE
Simplified getMenuItem so that arrays of children can be passed in.

### PR DESCRIPTION
**Pull request by AlastairTaft**
This change allows you to do the following

```js
<ContextMenu>
  {['Menu 1', 'Menu 2'].map(item => <Item>{item}</Item>)}
</ContextMenu>
```

### CODE REVIEW

**Comment by fkhadra** [comment]
Hello @AlastairTaft,

Appreciate your contribution.

I'm wondering if there is any benefit using your method. If I'm not mistaken we can't set the onClick props to the `Item` component in that case. Correct me if I'm wrong.

```js
<ContextMenu>
  {['Menu 1', 'Menu 2'].map(item => <Item>{item}</Item>)}
</ContextMenu>
```

**Comment by AlastairTaft** [comment]
If I understand correctly you could still do something like this if you want to pass in an onClick method for each item

```js
<ContextMenu>
  {['Menu 1', 'Menu 2'].map(item => <Item 
    onClick={() => this.handleOnClick(item)}
  >
    {item}
  </Item>)}
</ContextMenu>
```
As far as the change goes I don't think it is altering any existing behaviour. I don't think you need to do an array check because the `React.Children` methods figure out if it's a single element or collection, therefor as long as you stick to the React methods and don't use native array methods you don't need to check for the difference.

**Comment by fkhadra** [comment]
@AlastairTaft I was confused by the snippet but after reading your code more carefully I totally agree with you 😁

**Comment by AlastairTaft** [comment]
Thanks for merging :)

**Pull request merged**
