### PR TITLE
custom x/y position from props

### PR DESCRIPTION
**Pull request by evansjohnson**

### CODE REVIEW

**Comment by fkhadra** [comment]
Hello @evansjohnson,

Sorry for the very very late reply. I was very very busy.

Instead of using `props`, I'm wondering if it's not better to introduce a third parameter like `position`(not sure for the name) as follow:

```js
contextMenu.show({
id: menuId,
position: {
  x: customX,
  y: customY
}
})
```
I'm suggesting that because `props` is passed down to the `Item` onClick callback. It is not supposed to affect the `Menu` behavior. Also, I think that it's safer to use a third parameter to avoid any conflicts with end user's props.

I may be wrong, what do you think about that ?

**Comment by ronaiza-cardoso** [comment]
Can I have one sample on how to do this?

**Comment by doanhuyc** [comment]
this feature would be really helpful

**Comment by fkhadra** [comment]
This feature will be available when v5 is released. You can follow the [PR](https://github.com/fkhadra/react-contexify/pull/152). I'm currently rewriting the documentation. You can already play with the v5 by running 

```js
yarn add react-contexify@beta

npm install react-contexify@beta
```

**Pull request closed without merging**
