### PR TITLE
Disableguard

### PR DESCRIPTION
**Pull request by sielay**
#41 + ability to pass function that checks if item should be disabled

### CODE REVIEW

**Comment by fkhadra** [comment]
Hey @sielay,

I'll review the pull request during this weekend. Thanks

**Comment by fkhadra** [comment]
@sielay could you provide an example of how it works ?

Thanks

**Comment by sielay** [comment]
From actual project:

**Passing data**

```jsx
<ContextMenuProvider
    id="attachment-menu"
    className="inputIcon"
    renderTag="div"
    event="onClick"
    data={{
        callback: this.onAttachement.bind(this)
    }}
    >
        <img src="/brand/assets/sprites/add.svg" alt="Add attachment" />
</ContextMenuProvider>
```

```jsx
<ContextMenu
                    id="attachment-menu"
                    animation="pop">
                    <Item onClick={(...args) => (upload(args[3]))}>Upload</Item>
                    <Item onClick={(...args) => (pickFromLibrary(args[3]))}>Library Item</Item>
</ContextMenu>
```

**Disable guard**
```jsx
<If check={this.checkEncrypt.bind(this)}>
                <Item
                    onClick={(...args) => this.decrypt(args[3].comment, args[3].decrypt)}
                    disableGuard={this.isAttachment.bind(this)}
                >Decrypt</Item>
            </If>
```

You can see there `If` component I added as it was easier to do conditional rendering using your lib, here is component code:

```tsx
import * as React from "react";
import { ReactNode } from "react";

export class If extends React.Component {
    public props: Readonly<{ children?: ReactNode }> & Readonly<{
        outerData?: any,
        check: (outerDatadata: any) => boolean,
        render?: (data) => any 
    }>;

    constructor(props) {
        super(props);
        console.log("IF constructor", props, this);
    }

    public cloneItem = item => React.cloneElement(item, {
        outerData: this.props.outerData || item.props.outerData
    });

    public render() {

        if (this.props.check(this.props.outerData)) {

            if (this.props.render) {
                return this.props.render(this.props.outerData);
            }

            return React.Children.map(
                React.Children.toArray(this.props.children),
                this.cloneItem,
            );
        }
        return null;
    }
}

```

**Comment by sielay** [comment]
Heh. Yes there is a case for it. I mixed your lib with react-selection ended up having context providers that overlapped. I will try to provide more code examples. I like your suggestions. Can we park it for a week? Need some time to apply changes. Thanks for reviw.

**Comment by sielay** [comment]
Sorry for delay. I had loads of work. Will try to present clear version with examples soon.

**Comment by fkhadra** [comment]
Hello,

Actually, I rewrote a big part of the library. It's on the next branch. I already made the change to the disable props and also the data to the contextmenuprovider.

I'll make a rebase when it's ready so you won't lose your contribution

**Comment by sielay** [comment]
I am closing this PR. I will create new, consolidated with `If` component

**Pull request closed without merging**
