### PR TITLE
Added menu shown & hidden callbacks

### PR DESCRIPTION
**Pull request by Phault**
Needed this myself and noticed someone else did too.  #95

### CODE REVIEW

**Comment by Phault** [comment]
Hmmm.. Not sure what to do about the code duplication in unit tests that codeclimate is complaining about. Duplicated code seems kind of expected in unit tests, no?

**Comment by fkhadra** [comment]
Hello @Phault,

Thanks for the PR. I fixed the code climate issue(just needed to approve).

**Comment by Phault** [comment]
@fkhadra Alright, that sounds good.

**Comment by Phault** [comment]
@fkhadra I see you assigned me and didn't merge the PR. Am I supposed to do something?

**Pull request merged**
